@startuml model

class Carte{
    - valeur: int
    - couleur: enum Couleur
    + Carte(): Carte
    + getValeur(): int
    + getCouleur(): Couleur
    + setValeur(int valeur)
    + setCouleur(Couleur couleur)
}

class Combinaison{
    - cartes: Card_list
    - type: enum Type
    + Combinaison(): Combinaison 
    + getType(): Type 
    + getScore(): int 
}

class Joueur{
    - id_joueur: int
    - pied: List<Carte>
    + Joueur(): Joueur
    + getPied(): List<Carte>
    + getId(): int
    + setId(int new_id)
    + removeCarte(Carte carte)
    + addCarte(Carte carte)
    + nombreDeCartes(): int
}

class Card_list{
    - cartes: List<Carte>
    + nombreDeCartes(): int 
    + ajouterCarte(Carte new_carte) 
    + getCartes(): List<Carte> 
}

Combinaison --|> Card_list
Joueur --|> Card_list
Card_list --> Carte


@enduml