@startuml view

interface View{
    + afficherFrontiere(Frontiere frontiere);
    + afficherJoueur(Joueur J);
    + afficherMessage(String message);
    + afficherBorne(Borne borne);
    + afficherWinner(Joueur winner);
    + void afficherTour(Joueur active_player)
    + void afficherDebut()

    + select_card(Joueur J): Carte
    + select_borne(Joueur J, Frontiere F): Borne
    + select_revendication(Frontiere F): int
    + select_ia(int id_joueur, int nivmax_ia): Joueur
}

class ConsoleView{

}

ConsoleView ..|> View

@enduml
