@startuml view

interface View{
    + afficherFrontiere(Frontiere frontiere);
    + afficherJoueur(Joueur J);
    + afficherMessage(String message);
    + afficherBorne(Borne borne);

    + select_card(Joueur J);
    + select_borne(Joueur J, Frontiere F);
    + select_revendication(Frontiere F);
}

class Console{

}

Console ..|> View

@enduml